### ISSUE TITLE
image quality default 

### ISSUE THREAD

**Issue by Marc-pi** [pi-module/news#46]
(for News and Guide also)

* Don't put 100 as default quality, because a jpeg with 100 generates a heavier jpeg (it is a jpeg norm limitation).
   * by default, let empty the field so Imagine make use its default value (75), unless the admin sets another value in configs so that adding a new picture with this empty field works also
   * or put 75 (with the hope that Imagine does not change its rule)
* i guess you added only jpeg quality setting (not the png, right?)
   * so rename the config option `Image quality (jpeg)`.
   * add under `empty equals 75` or `default is 75`

http://imagine.readthedocs.org/en/latest/usage/introduction.html

**Comment by voltan** [comment]
OK , I check it again and it work fine for both of PNG and JPG , and default set to 75

**Comment by Marc-pi** [comment]
as long as i understand, they use only percents and convert if png to png scale with rounded function, so we can use a single config value.
NB  i do not use personaly png

````
// Beaware that compression level for png works the other way around.
// For PNG 0 means no compression and 9 means highest compression level.
````
so we have for 75 JPEG compression level (relative low compression)
round((100-75) * 9 / 100) =  2,25 ~> 2 
=> so 75% JPEG here equiv to 2 PNG (the doc indicates 7 as default i.e. high compression)

=> ok, as long as i understand, the imagine doc is not up to date !
